import typing as t
from enum import Enum

class Kernel:
    """
    A kernel.
    """

    def __new__(cls, size: int = 3, short_name: str = "", long_name: str = "") -> 'Kernel':
        """
        New kernel.

        :param size:
        :param short_name:
        :param long_name:
        """
        ...
    @staticmethod
    def simple_rw() -> 'Kernel': ...
    @staticmethod
    def biased_rw(probability: float, direction: 'Direction') -> 'Kernel': ...
    @staticmethod
    def correlated_rw(persistence: float) -> list['Kernel']: ...
    @staticmethod
    def biased_correlated_rw(probability: float, direction: 'Direction', persistence: float) -> list['Kernel']: ...
    def size(self) -> int: ...
    def set(self, x: int, y: int, val: float): ...
    def at(self, x: int, y: int) -> float: ...
    def rotate(self, degrees: int):
        """
        Rotate it.

        :param degrees:
        :return:
        """
        ...
    def name(self, short: bool) -> str: ...

class Direction(Enum):
    North = 1
    East = 2
    South = 3
    West = 4
    Stay = 5

class Walk:
    def len(self) -> int: ...
    def is_empty(self) -> bool: ...
    def __iter__(self) -> t.Iterable['Walk']: ...
    def frechet_distance(self, other: 'Walk') -> float: ...
    def directness_deviation(self) -> float: ...
    def translate(self, by: 'XYPoint') -> 'Walk': ...
    def scale(self, by: 'XYPoint') -> 'Walk': ...
    def rotate(self, degrees: float) -> 'Walk': ...
    def plot(self, filename: str): ...
    @staticmethod
    def plot_multiple(walks: list['Walk'], filename: str): ...
    def __repr__(self) -> str: ...
